base_url = "https://douglops.github.io/blog"
title = "Douglops - notes and banters"
description = "Tales from the neverending sea of diffs"

compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]


[extra]
author = "Douglas Oliveira"

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"
